PUT http://localhost:3001/api/blogs/5c698f627f3d3f0c1c21129b
Content-Type: application/json

{
  "title": "TestiBlogi",
  "author": "Teuvo Testaaja",
  "url": "t-testaaja.blogsnort.orc",
  "likes": 11
}